### ISSUE TITLE
Probleme de Persistence provider

### ISSUE THREAD

**Issue by shymine** [arnobl/WebEngineering-INSA#1]
Bonjour, je suis un de vos étudiants à l'INSA et dans le but de travailler de nouveau sur le tp par moi même, j'ai cloné le git. Cependant, lors de l'exécution du test JPACalendar, j'ai une erreur qui me fut remonté intitulée:

" javax.persistence.PersistenceException: No Persistence provider for EntityManager named agendapp " 
dont la trace est la suivante : 

" at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:85)
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:54)
	at fr.insarennes.TestJPACalendar.setUp(TestJPACalendar.java:31)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)"

J'ai cherché sur internet ce qui pouvait causer cette erreur, et j'ai remarqué que dont le fichier persistence.xml, aucun provider n'était défini pour la persistence-unit. Cependant, même après avoir ajouté un provider au sein de la persistence-unit ("<provider>org.hibernate.jpa.HibernatePersistenceProvider</provider>"), j'obtiens toujours cette erreur. Malgré mes recherches, je n'ai pas réussi à comprendre ce qui causait cette erreur. Or, durant le TP, aucun problème de ce type n'est apparu. Sauriez vous ce qui cause cette erreur?
Je vous remercie de votre attention.
Timothée Neitthoffer

**Comment by arnobl** [comment]
Bonjour,
Cette erreur peut avoir plusieurs origines :
- il peut manquer des annotations JPA sur les classes du modèles
- le fichier persistence.xml peut ne pas être correct (ce qui n'est pas le cas ici)

En bref, vérifiez les annotations JPA.

Cordialement,
A.
